custom_header:
  background: 'rgba(255, 152, 0, 0.01)'
  swipe_animate: fade
  swipe_prevent_default: true
  compact_mode: true
  button_icons:
    voice: mdi:microphone
    options: mdi:dots-vertical
resources:
  - url: /local/community/lovelace-card-preloader/lovelace-card-preloader.js
    type: js
  - url: /local/lovelace/card/mini-graph-card-bundle.js
    type: module
  - url: /local/community/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /local/community/roku-card/roku-card.js
    type: module
  - url: /local/lovelace/card/card-modder.js?v=1
    type: js
  - url: /local/lovelace/card/card-tools.js?track=true
    type: js
  - url: /local/lovelace/card/weather-card/dist/weather-card.js
    type: js
  - url: /local/lovelace/card/thermostat-card/thermostat-card.js
    type: module
  - url: /local/lovelace/card/calendar-card.js
    type: js
  - url: /local/lovelace/card/popup-card.js
    type: js
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /local/community/spotify-playlist-card/spotify-playlist-card.js
    type: js
title: Home
background: var(--background-image)
views:
  - id: 0  # Automatically created id
    title: Home
    icon: mdi:home-assistant
    cards:
      - type: vertical-stack
        cards:
            - type: custom:weather-card
              entity: weather.bardello
              icons: "/local/lovelace/card/weather-card/dist/icons/"
              current: true
              details: true
              forecast: true
            - type: custom:calendar-card
              title: "My Calendar"
              progressBar: true
              entities:
                - calendar.festivita_in_italia
                - calendar.le_partite_della_juventus_vecchiasignoracom
                - calendar.p
            - type: glance
              entities:
                - sensor.plex
      - type: vertical-stack
        cards:
              - type: iframe
                url: https://embed.windy.com/embed2.html
                aspect_ratio: 75%             
              - type: glance
                entities:
                  - person.mbp_francesco
                  - person.francesco_2
                  - sensor.badlogin
                  - sensor.last_boot
                  - binary_sensor.updater
                  - sun.sun
                  - sensor.time
                  - sensor.date
              - type: horizontal-stack
                cards:
                  - type: entity-button
                    name: Restart
                    entity: script.restart_ha
                    tap_action: 
                      action: toggle
                  - type: entity-button
                    name: Stop
                    entity: script.stop_ha
                    tap_action: 
                      action: toggle
                  - type: entity-button
                    name: Reboot
                    entity: script.reebot_pi
                    tap_action: 
                      action: toggle                 
                  - type: entity-button
                    name: Shoutdown
                    entity: script.shoutdown_pi
                    tap_action: 
                      action: toggle 
      - type: vertical-stack
        cards:
              - type: entities
                title: ZigBee
                show_header_toggle: false
                entities:
                  - entity: input_boolean.zigbee_permit_join
                  - entity: timer.zigbee_permit_join
                  - entity: sensor.zigbee2mqtt_bridge_state
                  - entity: switch.zigbee2mqtt_main_join
                  - entity: input_select.zigbee2mqtt_log_level
                  - entity: automation.zigbee2mqtt_log_level
              - type: entities
                title: Backup Dropbox
                show_header_toggle: false
                entities:
                  - automation.hassio_backup
                  - input_datetime.backup_time
                  - input_select.backup_day

  - title: Camera Francesco
    icon: mdi:bed-empty
    popup_cards:
     remote.roku_nowtv:
        title: NOW TV
        card:
            type: 'custom:roku-card'
            entity: media_player.roku_nowtv
            tv: true
            apps:
              - id: Now TV
                icon: /local/nowtv.png
              - id: YouTube
                icon: /local/YouTube.png
              - id: DAZN
                icon: /local/dazn.png
            volume_up:
              tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                entity_id: remote.roku_nowtv
                command: volume_up
            volume_down:
              tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                entity_id: remote.roku_nowtv
                command: volume_down              
    cards:
      - type: vertical-stack
        cards:
              - type: horizontal-stack
                cards:
                  - type: light
                    entity: light.lampadario           
                  - type: light
                    entity: light.luce_letto
              - type: horizontal-stack
                cards:
                  - type: light
                    entity: light.striscia_led_rgb 
              - type: entities
                entities:
                    - input_select.luci_timer
                    - input_number.minuti_luci
                    - timer.light_on                
              - type: glance
                entities:
                    - binary_sensor.finestra_camera
                    - sensor.finestra_camera_battery
              - type: entity-button
                tap_action:
                  action: toggle
                entity: switch.sonoff_1 

      - type: vertical-stack
        cards:
              - type: custom:mini-media-player
                entity: media_player.tv_camera
                artwork: cover
                hide:
                  volume: false
                  source: false
                  power_state: false
              - type: entities
                show_header_toggle: false
                entities:
                  - remote.roku_nowtv
              - type: horizontal-stack
                cards:
                  - type: entity-button
                    entity: script.timer_spegnimento
                    tap_action: 
                      action: toggle
                  - type: entity-button
                    entity: script.spegni_accendi
                    tap_action: 
                      action: toggle
                  - type: entity-button
                    name: Source modalità
                    entity: script.source
                    tap_action: 
                      action: toggle
              - type: horizontal-stack
                cards:
                  - type: entity-button
                    name: Canale Precedente
                    entity: script.mc
                    tap_action: 
                      action: toggle
                  - type: entity-button
                    name: Canale Successivo
                    entity: script.pc
                    tap_action: 
                      action: toggle
                  - type: entity-button
                    name: Canale Memorizzato
                    entity: script.rc
                    tap_action: 
                      action: toggle             
              - type: horizontal-stack
                cards:
                  - type: entity-button
                    entity: script.av
                    tap_action: 
                      action: toggle
                  - type: entity-button
                    entity: script.bv
                    tap_action: 
                      action: toggle
                  - type: entity-button
                    entity: script.mv
                    tap_action: 
                      action: toggle
              - type: horizontal-stack
                cards:
                  - type: entities
                    show_header_toggle: false
                    entities:
                      - input_select.numeri_canali
                      - script.seleziona_numero
              - type: horizontal-stack
                cards:
                  - type: entities
                    show_header_toggle: false
                    entities:
                      - input_select.canali_preferiti
                      - script.seleziona_preferiti
              - type: horizontal-stack
                cards:
                  - type: entity-button
                    entity: script.ok
                    tap_action: 
                      action: toggle
                  - type: entity-button
                    entity: script.info
                    tap_action: 
                      action: toggle

      - type: vertical-stack
        cards:
              - type: custom:thermostat-card
                title: Camera
                entity: climate.termostato_camera
                chevron_size: 100
                idle_zone: 2
                highlight_tap: true
                no_card: true
                hvac:
                  states:
                    'Off': 'off'
                    'Cooling': 'cool'
                    'Heating': 'heat'
                  attribute: operation_mode
              - type: horizontal-stack
                cards:
                  - type: custom:mini-graph-card
                    entities: sensor.humidity
                    line_color: blue
                    line_width: 8
                    font_size: 75
                  - type: custom:mini-graph-card
                    entities: sensor.pressure
                    line_color: var(--accent-color)
                    line_width: 8
                    font_size: 75
              - type: picture-entity
                title: Francesco PC
                entity: switch.francesco_pc
                image: /local/lovelace/image/pc-francesco_on.jpg

      - type: vertical-stack
        cards:
              - type: map
                default_zoom: 30
                entities:
                  - entity: person.mbp_francesco
                  - entity: person.francesco_2
                  - zone.home
                  - zone.nonna       
              - type: picture-glance
                image: /local/lovelace/image/radio.jpg?auto=compress&cs=tinysrgb&dpr=2&h=295&w=490
                title: Radio
                entities:
                  - input_text.radio_1_ip_address
                  - input_text.radio_2_ip_address
                  - script.urlradio1
                  - script.urlradio2
              - type: picture-glance
                title: Sveglia
                entities:
                  - input_boolean.attivazione_sveglia
                  - input_datetime.sveglia_time
                  - input_number.volume_sveglia
                  - input_select.tipo_di_sveglia
                  - input_select.canzoni_sveglia
                  - script.riproduco_sveglia
                  - script.ferma_sveglia
                image: /local/lovelace/image/sveglia_on.jpg?auto=compress&cs=tinysrgb&dpr=2&h=295&w=490   
              - type: entity-button
                tap_action:
                  action: toggle
                entity: switch.cellulare                
               
  - title: esterno
    icon: mdi:door
    cards:
      - type: horizontal-stack
        cards:
              - type: custom:mini-graph-card
                entities: sensor.humidity_esterna
                line_color: blue
                line_width: 8
                font_size: 75
              - type: custom:mini-graph-card
                entities: sensor.temperature_esterna
                line_color: var(--accent-color)
                line_width: 8
                font_size: 75    
      - type: entities
        title: Tende Da sole
        show_header_toggle: false
        entities:
              - cover.tenda_camera_1
              - input_number.pos_tenda_1
              - cover.tenda_camera_2
              - input_number.pos_tenda_2
              - cover.tende_da_sole
            
  - title: Allarme
    icon: mdi:alarm-light-outline
    cards:
      - type: alarm-panel
        entity: alarm_control_panel.my_allarm
      - type: entities
        entities:
            - sensor.alarm_sensor

  - title: Musica
    icon: mdi:music-box
    cards:
      - type: vertical-stack
        cards:
            - type: custom:mini-media-player
              entity: media_player.spotify
              icon: mdi:spotify
              artwork: cover
              hide:
                volume: false
                source: false
                power_state: false
            - type: custom:mini-media-player
              entity: media_player.echo_dot_di_francesco
              icon: mdi:amazon-alexa
              artwork: cover
              hide:
                volume: false
                source: false
                power_state: false
            - type: custom:mini-media-player
              entity: media_player.home
              icon: mdi:google-home
              artwork: cover
              hide:
                volume: false
                source: false
                power_state: false
            - type: custom:mini-media-player
              entity: media_player.camera
              icon: mdi:google-home
              artwork: cover
              hide:
                volume: false
                source: false
                power_state: false
            - type: custom:mini-media-player
              entity: media_player.musica
              artwork: cover
              hide:
                volume: false
                source: false
                power_state: false
            - type: custom:mini-media-player
              entity: media_player.gcamera
              artwork: cover
              hide:
                volume: false
                source: false
                power_state: false
      - type: vertical-stack
        cards:
          - type: custom:spotify-playlist-card
            sensor: sensor.spotifyplaylist  
            playback_method: spotcast
            speaker_entity: media_player.camera
            gradient_level: 0.7
            grid_gap: '8px'
            show_playlist_titles: true
            shuffle: true
            columns: 4

  - title: Rete
    icon: mdi:lan
    cards:
      - type: vertical-stack
        cards:
            - type: custom:mini-graph-card
              name: SPEEDTEST
              icon: mdi:speedometer
              entities:
                - entity: sensor.speedtest_download
                  name: DOWNLOAD
                - entity: sensor.speedtest_upload
                  name: UPLOAD
                - entity: sensor.speedtest_ping
                  name: PING
            - type: custom:mini-graph-card
              name: INFO CPU SERVER 
              icon: mdi:server
              entities:
                - entity: sensor.glances_cpu_load
                  name: CPU LOAD SERVER
                - entity: sensor.glances_cputin_temp_2
                  name: CPU TEMP SERVER
                - entity:  sensor.glances_cpu_used
                  name: CPU USED SERVER
            - type: horizontal-stack
              cards:
                - type: picture-entity
                  title: Unifi Security Gateway 
                  entity: device_tracker.ugw3
                  image: /local/lovelace/image/usg.jpg  
                - type: picture-entity
                  title: Unifi AP AC LR
                  entity: device_tracker.u7lr
                  image: /local/lovelace/image/unifi_ap.jpg
      - type: vertical-stack
        cards:
                    - type: custom:mini-graph-card
                      name: INFO RAM SERVER
                      icon: mdi:server
                      entities:
                        - entity: sensor.glances_ram_free
                          name: RAM FREE SERVER
                        - entity: sensor.glances_ram_used
                          name: RAM USED SERVER
                        - entity: sensor.glances_ram_used_percent
                          name: RAM % SERVER
                    - type: custom:mini-graph-card
                      name: INFO DISK SERVER
                      icon: mdi:server
                      entities:
                        - entity: sensor.glances_free_2
                          name: DISK FREE SERVER
                        - entity: sensor.glances_used_2
                          name: DISK USED SERVER
                        - entity: sensor.glances_used_percent_2
                          name: DISK % SERVER
                    - type: horizontal-stack
                      cards:
                        - type: picture-entity
                          title: Unifi Switch 8 60W
                          entity: device_tracker.us8p60
                          image: /local/lovelace/image/us860w.jpeg
                        - type: picture-entity
                          title: Unifi Controller
                          entity: device_tracker.ubuntu
                          image: /local/lovelace/image/unifi-controller.png        
      - type: vertical-stack
        cards:
                    - type: custom:mini-graph-card
                      name: INFO RAM HASSOS
                      icon: mdi:home-assistant
                      entities:
                        - entity: sensor.memory_free
                          name: RAM FREE HASSOS
                        - entity: sensor.memory_use
                          name: RAM USED HASSOS
                    - type: horizontal-stack
                      cards:
                        - type: custom:mini-graph-card
                          name: DISK USED HASSOS
                          icon: mdi:home-assistant
                          entities:
                            - entity: sensor.disk_use_percent
                        - type: custom:mini-graph-card
                          name: PROCESSOR USED HASSOS
                          icon: mdi:home-assistant
                          entities:
                            - entity: sensor.processor_use
                    - type: glance
                      entities:
                        - sensor.myip
                        - automation.notify_when_external_ip_changes
                    - type: glance
                      entities:
                        - sensor.ssl

  - title: Prova
    icon: mdi:lightbulb-outline
    cards:
      - type: light
        entity: light.luce_test
      - type: iframe
        url: /local/player/player.html 
        aspect_ratio: 58%         
